name: "Sync GitHub to GitLab Action"
description: "A Github Action which will sync a GitHub repository to GitLab as a mirror."
inputs:
  destination_repository:
    description: "Gitlab Repository URL to sync to in SSH format."
    required: true
  destination_ssh_key:
    description: "SSH Private key to use to connect to remote repository."
    required: true
  destination_branch_name:
    description: "Destination branch name to sync to."
    required: false
    default: "main"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: git-commit
  color: red